# -*- coding: utf-8 -*-
"""npz_to_images_luna.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GRp4Bwk9-I0YZ3xeAdxjPRE3MO5Zo2O5
"""

import matplotlib.pyplot as plt
import numpy as np
import cv2
import PIL
from PIL import Image
import os

# EDIT: change path to npz file
dfile = "/projects01/VICTRE/yubi.mamiya/minimal-diffusion/sample_imgs_output_test/UNet_melanoma-250-sampling_steps-600_images-class_condn_True.npz"
img_dir_path = "/projects01/VICTRE/yubi.mamiya/minimal-diffusion/synth_data/ITA_images/"

images = np.load(dfile)["arr_0"]

# EDIT: change the number of images in npz file
for i in range(0, 600):
    # EDIT: change the offset for the saved images
    k = i + 12500
    im_file_name = f"ITA_{k}.png"
    img_path = os.path.join(img_dir_path, im_file_name)
    im = Image.fromarray(images[i])
    im.save(img_path)