# -*- coding: utf-8 -*-
"""ITA_summary_luna.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14gAlAEa7qsmnqNB7pt0ycW3xLXtET-mR
"""

from skimage import io, color
import numpy as np
import cv2
from PIL import Image
import matplotlib.pyplot as plt
import os
import pandas as pd
import shutil
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

data_dir = 'projects01/VICTRE/yubi.mamiya/minimal-diffusion/synth_data/'

# this is a cleaned csv with only the image_id's of images with a good mask
skin_color_df = pd.read_csv(data_dir + 'skin_color.csv', delimiter=',')
skin_color_df.head()

"""* <= 10 is dark
* <= 19 is tan1
* <= 28 is tan2
* <= 34.5 is int1
* <= 41 is int2
* <= 48 is lt1
* <= 55 is lt2
* >= 55 is very_lt
"""

# count number of ITA values
dark_num = skin_color_df['color'].value_counts()['dark']
tan1_num = skin_color_df['color'].value_counts()['tan1']
tan2_num = skin_color_df['color'].value_counts()['tan2']
int1_num = skin_color_df['color'].value_counts()['int1']
int2_num = skin_color_df['color'].value_counts()['int2']
lt1_num = skin_color_df['color'].value_counts()['lt1']
lt2_num = skin_color_df['color'].value_counts()['lt2']
very_lt_num = skin_color_df['color'].value_counts()['very_lt']

color_vals = [dark_num, tan1_num, tan2_num, int1_num, int2_num, lt1_num, lt2_num, very_lt_num]
colors = ['dark', 'tan1', 'tan2', 'int1', 'int2', 'lt1', 'lt2', 'very_lt']

plt.bar(colors, color_vals, color ='maroon', width = 0.4)
plt.xlabel("Skin Colors")
plt.ylabel("Number of images")
plt.title("Distribution of skin color in synthetic images")
plt.show()

# save plot
plt.savefig(data_dir + 'skin_color_plot.png')